language: julia
dist: trusty
sudo: true
os:
  - linux
  - osx
julia:
  - 0.6
  - 0.7
  - nightly
notifications:
  email: false
# env:
#   - PYTHON=""
before_install:
   - (sudo apt-get -qq update && sudo apt-get install -y python python-pip && sudo pip install matplotlib && sudo pip install git+https://github.com/lanpa/tensorboard-pytorch)
script:
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.build("Tensorboard")'
  - julia -e 'Pkg.update()'
  - julia -e 'Pkg.add("MLDatasets")'
  - julia -e 'Pkg.test("Tensorboard", coverage=true)'
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly
