language: julia
dist: trusty
sudo: true
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
env:
  - DOCUMENTER_DEBUG="true" CONDA_JL_VERSION="2" PYTHON=""
script:
  - pip install git+https://github.com/lanpa/tensorboard-pytorch
  - julia -e 'Pkg.clone("https://github.com/zenna/Spec.jl")'
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.build("TensorboardX")'
  - julia -e 'Pkg.add(MLDatasets)'
  - julia -e 'Pkg.test("TensorboardX", coverage=true)'
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly
