language: julia
dist: trusty
sudo: true
os:
  - linux
  - osx
julia:
  - 0.6
  - 0.7
  - nightly
notifications:
  email: false
env:
  - DOCUMENTER_DEBUG="true" CONDA_JL_VERSION="2" PYTHON=""
script:
  # - sudo pip install git+https://github.com/lanpa/tensorboard-pytorch
  - julia -e 'Pkg.add("Conda"); using Conda; Conda.add("tensorboardX")'
  - julia -e 'Pkg.build("Tensorboard")'
  - julia -e 'Pkg.update()'
  - julia -e 'Pkg.add("MLDatasets")'
  - julia -e 'Pkg.add("Tests")'
  - julia -e 'Pkg.test("Tensorboard", coverage=true)'
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly
