name = "Tensorboard"
uuid = "0b0dfcba-97db-11e8-112a-b5f40c7258d9"
authors = ["Zenna Tavares <zenna@mit.edu>"]
version = "0.1.0"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]